schema_version: 1

context:
  name: python-pam
  version: "2.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 04598b0fba9e3fa290f27e4f8d1762a9d61b75f1e38b53e9d8d861af53eb0d2a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=2.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pam
      pip_check: true
      python_version:
        - "${{ python_min }}.*"
        - "*"

about:
  summary: Python PAM module using ctypes, py3
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/FirefighterBlu3/python-pam

extra:
  recipe-maintainers:
    - timkpaine
